# StaplePlugin Configuration
motd: Welcome to the server!
help-message: Placeholder Text
rules-message: Placeholder Text
vote-message: "<gold><st>                                                             </st></gold>
                \n                           <b><gold>Vote</gold></b>
                \n
                \n         <gold>Vote for the server at:</gold>
                \n         <yellow><click:open_url:'url'>https://creative-central.net/vote</click></yellow>
                \n<gold><st>                                                             </st></gold>"

# Spawn
spawn-x: 0
spawn-y: 0
spawn-z: 0

# MySQL Configuration
mysql:
  host: hostname
  port: 3360
  database: database
  username: username
  password: password