# StaplePlugin Configuration
motd: Welcome to the server!
help-message: "<gold><st>                                                             </st></gold>
                \n                           <b><gold>Help</gold></b>
                \n
                \n         <gold>View info on how to play at:</gold>
                \n         <yellow><click:open_url:'url'>https://creative-central.net/help</click></yellow>
                \n<gold><st>                                                             </st></gold>"
rules-message: "<gold><st>                                                             </st></gold>
                \n                           <b><gold>Rules</gold></b>
                \n
                \n         <gold>View the server rules at:</gold>
                \n         <yellow><click:open_url:'url'>https://creative-central.net/rules</click></yellow>
                \n<gold><st>                                                             </st></gold>"
vote-message: "<gold><st>                                                             </st></gold>
                \n                           <b><gold>Vote</gold></b>
                \n
                \n         <gold>Vote for the server at:</gold>
                \n         <yellow><click:open_url:'url'>https://creative-central.net/vote</click></yellow>
                \n<gold><st>                                                             </st></gold>"

# Spawn
spawn-x: -261.5
spawn-y: 101
spawn-z: -261.5

# MySQL Configuration
mysql:
  host: hostname
  port: 3360
  database: database
  username: username
  password: password