name: cc-staple
version: '1.0'
main: net.cc.staple.StaplePlugin
description: A general purpose plugin for Creative Central
authors: [ SpektrSoyuz ]
api-version: '1.21'
permissions:
  cc.command.broadcast:
    description: 'Broadcast a message to the entire server'
  cc.command.enderchest:
    description: 'Access your ender chest'
  cc.command.gamemode:
    description: 'Switch your gamemode'
  cc.command.hat:
    description: 'Put on a hat'
  cc.command.help:
    description: 'View the help page'
  cc.command.item:
    description: 'Summon an item'
  cc.command.jump:
    description: 'Jump to a location'
  cc.command.ping:
    description: 'Pong!'
  cc.command.playertime:
    description: 'Set the player time'
  cc.command.respawn:
    description: 'Respawn'
  cc.command.rules:
    description: 'View the rules page'
  cc.command.setspawn:
    description: 'Set the server spawn'
  cc.command.spawn:
    description: 'Teleport to spawn'
  cc.command.speed:
    description: 'Set your speed'
  cc.command.teleport:
    description: 'Teleport to a player'
  cc.command.top:
    description: 'Teleport to the top block'
  cc.command.tpa:
    description: 'Send and receive teleport requests'
  cc.command.tptoggle:
    description: 'Toggle tpa requests'
  cc.command.vote:
    description: 'View the vote page'